services:
  - type: web
    plan: free
    name: ub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m Yuvaraj
    repo: https://github.com/YesawiniYuvaraj/Pyro-Userbot-V1.git      
    branch: main
    envVars:
      - key: SESSION 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: SESSION 
        sync: false
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: GROUP_ID
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
    autoDeploy: false
